### PR TITLE
Add discover

### PR DESCRIPTION
**Pull request by dhylands**
This adds discoverAdapters and discoverDevices.

I started to look at hooking them in, but I wasn't sure exactly where you wanted them.

I also experimented a bit with jsDoc and added a bit of jsDoc documentation. If this looks reasonable, I'll continue to add documentation this way.

You can install jsdoc by doing `npm install jsdoc` and then just run `./node_modules/.bin/jsdoc .` and open `out/index.html` to see the generated documentation.

### CODE REVIEW

**Comment by dhylands** [comment]
Added controllers for adapters/, adapters/:adapterId/, adapters/:adapterId/devices/ and adapters/:adapterId/devices/:deviceId.

These are primarily for debug to query information directly from the adapter rather than what's filterd by the db. This also fixes up some minor bugs in discoverDevices & discoverAdapters now that the functions are actually exercised.

**Comment by benfrancis** [comment]
Cool.

Haven't reviewed yet because I think you omitted some files from the commit.

```
Error: Cannot find module './controllers/adapters_controller'
```

**Comment by dhylands** [comment]
Right you are.

**Comment by benfrancis** [comment]
I believe this was covered in another pull request

**Pull request closed without merging**
