### PR TITLE
Updated README to add more dependency information.

### PR DESCRIPTION
**Pull request by dhylands**
This adds the dependency information needed for open-zwave.

### CODE REVIEW

**Comment by benfrancis** [comment]
Thanks for documenting this.

I can't help but feel this could be made simpler, there are multiple ways of installing these pre-requisites and some of them aren't strictly necessary.

We could just write...

## Prerequisites
* [NodeJS](https://nodejs.org) ([Installation instructions](https://github.com/moziot/wiki/wiki/Installing-node))
* [OpenZWave](http://www.openzwave.com/) ([Installation instructions](https://github.com/moziot/wiki/wiki/Installing-openzwave))

...with links to their websites and a wiki page with our tips for installing on different operating systems.

For example, on Ubuntu I downloaded a Node binary from [nodejs.org](https://nodejs.org/en/download/) and OpenZWave from [openzwave.com](http://old.openzwave.com/downloads/) and it worked fine. No need for pkg-config or nvm or building openzwave myself. On Mac OS the openzwave-shared documentation says you can use HomeBrew to install openzwave with "brew install open-zwave", although I haven't been able to get it to work with that method.

**Comment by benfrancis** [comment]
Proposed an alternative here https://github.com/moziot/gateway/pull/23

Let me know if you think this is better.

I'm also wondering whether we can make some dependencies optional. If someone only wants a Bluetooth gateway or a ZigBee gateway or a ZWave gateway there are some dependencies they won't need (e.g. building openzwave which adds complexity).

**Comment by dhylands** [comment]
I didn't want to just point at the pages, because they offer a bunch of alternatives, I wanted to document what we recommend.

I certainly don't mind having the instructions elsewhere (perhaps on the wiki or in a separate README file (like README-openzwave.md) and have the front page just refer to that.

I also think that having a script to install all of the right things is also pretty much the way to go. I think we're going to need it once we start doing Travis builds/testing.

For zwave in particular, building from source seems to be the recommended approach. The distros all tend to have older copies.

I'm all for making stuff optional. We just need to figure out how to make it work. I'm pretty sure that for something like zwave, we could make the adapter test to see if the libopenzwave.so file is available, and if not, don't enable the zwave adapter.

Currently it won't add the adapter if it doesn't find a dongle, but I think it might still need the lib.

**Comment by dhylands** [comment]
I filed #24

**Comment by benfrancis** [comment]
Yeah I think you're right this is only get more complicated so we're going to need a build script.

**Pull request merged**
